# Copyright (C) 2022 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.
---

version: '3'

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'clean'
      - task: 'dependencies'
      - task: 'build'
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  build:
    cmds:
      - task: 'build:frontend'
      - task: 'build:backend'
    desc: 'Build the Time Tracker app frontend and server application'

  build:frontend:
    cmds:
      - 'node_modules/.bin/vite build'
    desc: 'Build the Time Tracker app frontend for production'

  build:backend:
    cmds:
      - 'go build .'
    desc: 'Build the Time Tracker app server application'

  clean:
    cmds:
      - 'rm -fr dist node_modules timetracker'
    desc: 'Delete all buildable files and third-party dependencies'

  dependencies:
    cmds:
      - task: 'dependencies:javascript'
    desc: 'Run all dependency-installing-related tasks'

  dependencies:javascript:
    cmds:
      # <http://www.tiernok.com/posts/2019/faster-npm-installs-during-ci/>
      - 'npm ci --prefer-offline --no-audit'
    env:
      CI: true
    desc: 'Install JavaScript dependencies for building, development, and testing'

  development:
    cmds:
      - 'node_modules/.bin/vite'
    desc: 'Run the Vite development server'

  lint:
    cmds:
      - task: 'lint:javascript'
      - task: 'lint:golang'
    desc: 'Run all linting-related tasks'

  lint:golang:
    cmds:
      - task: 'lint:golang:golint'
      - task: 'lint:golang:staticcheck'
      - task: 'lint:golang:vet'

  lint:golang:golint:
    cmds:
      - 'golint -set_exit_status {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Golint'
    vars: &GOLANG_LINT_VARS
      GO_PACKAGES:
        sh: 'go list ./...'

  lint:golang:staticcheck:
    cmds:
      - 'staticcheck {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Staticcheck'
    vars: *GOLANG_LINT_VARS

  lint:golang:vet:
    cmds:
      - 'go vet {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Vet'
    vars: *GOLANG_LINT_VARS

  lint:javascript:
    cmds:
      - 'node_modules/.bin/eslint --ext .js,.vue src'
    desc: 'Lint JavaScript/Vue files with ESLint'

  preview:
    cmds:
      - task: 'build'
      - 'node_modules/.bin/vite preview'
    desc: 'Preview the Time Tracker production build locally'
