# Copyright (C) 2022 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

---
name: 'Lint Project'

on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: 'Lint project'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'

      - name: 'Set up Node environment'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '${{ matrix.node }}'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Ensure project builds, and run all linting and testing tasks'
        run: './bin/task ci'
    strategy:
      fail-fast: true
      matrix:
        node:
          - '16'
          - '17'
